export const GET_POKEMON = 'GET_POKEMON'
export const GET_NAME = 'GET_NAME'
export const GET_ID = 'GET_ID'
export const CREATE_POKEMON = 'CREATE_POKEMON'
export const IMAGEN  = 'IMAGEN'
export const ORDER_A_Z = 'ORDER_A_Z'
export const ORDER_ATAQUE = 'ORDER_ATAQUE'
export const TYPES = 'TYPES'
export const FILTER_API_DB = 'FILTER_API_DB'
export const TYPES_FILTER = 'TYPES_FILTER'
// export const  = ''
// export const  = ''

